
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-updater
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: node-updater
  template:
    metadata:
      labels:
        app: node-updater
    spec:
      tolerations:
      - operator: "Exists"
      hostPID: true
      hostNetwork: true
      initContainers:
      - name: updater
        image: debian:stable-slim
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-root
          mountPath: /host
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -ex
            if [ ! -f /host/var/lib/.node-updated ]; then
              echo "Node $(hostname): Running apt update/upgrade and configuring unattended-upgrades..."
              chroot /host /bin/bash -c "export DEBIAN_FRONTEND=noninteractive; apt-get update && apt-get -y upgrade && apt-get install -y unattended-upgrades"
              chroot /host /bin/bash -c "echo 'APT::Periodic::Update-Package-Lists \"1\";' > /etc/apt/apt.conf.d/20auto-upgrades"
              chroot /host /bin/bash -c "echo 'APT::Periodic::Unattended-Upgrade \"1\";' >> /etc/apt/apt.conf.d/20auto-upgrades"
              touch /host/var/lib/.node-updated
              echo "Node $(hostname): Update and configuration complete."
            else
              echo "Node $(hostname): Already updated. Skipping update."
            fi
      containers:
      - name: pause
        image: registry.k8s.io/pause:latest
        # This container does nothing but keep the pod alive.
      volumes:
      - name: host-root
        hostPath:
          path: /
